# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-14 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskusnyPrispevok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Napad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('textovy_popis', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorNapad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('popis', models.TextField()),
                ('clenovia', models.ManyToManyField(related_name='clenovia_teamu', to=settings.AUTH_USER_MODEL)),
                ('napady', models.ManyToManyField(blank=True, to='mapa.Napad')),
                ('zakladatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_teamu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vrstva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Zapis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=300)),
                ('datum', models.DateField()),
                ('kraj', models.CharField(max_length=300)),
                ('textovy_popis', models.TextField()),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
                ('napad', models.ManyToManyField(blank=True, to='mapa.Napad')),
                ('ucastnici', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('vrstvy', models.ManyToManyField(to='mapa.Vrstva')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zapis',
            field=models.ManyToManyField(to='mapa.Zapis'),
        ),
        migrations.AddField(
            model_name='diskusnyprispevok',
            name='zapis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.Zapis'),
        ),
    ]
